# Generated by Django 2.0.7 on 2019-11-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('raw_text', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('ack', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TradeTest',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('forex_account_number', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('forex_pair', models.CharField(max_length=255)),
                ('entry', models.FloatField()),
                ('action', models.CharField(max_length=255)),
                ('lotsize', models.FloatField()),
                ('stop_loss1', models.FloatField()),
                ('stop_loss2', models.FloatField()),
                ('stop_loss3', models.FloatField()),
                ('stop_loss4', models.FloatField()),
                ('stop_loss5', models.FloatField()),
                ('stop_loss_pips_planned', models.FloatField()),
                ('stop_loss_pips_actual', models.FloatField()),
                ('stop_loss_count', models.IntegerField()),
                ('take_profit1', models.FloatField()),
                ('take_profit1_adj', models.FloatField()),
                ('take_profit1_pips_planned', models.FloatField()),
                ('take_profit1_pips_actual', models.FloatField()),
                ('take_profit2', models.FloatField()),
                ('take_profit2_adj', models.FloatField()),
                ('take_profit2_pips_planned', models.FloatField()),
                ('take_profit2_pips_actual', models.FloatField()),
                ('take_profit3', models.FloatField()),
                ('take_profit3_adj', models.FloatField()),
                ('take_profit3_pips_planned', models.FloatField()),
                ('take_profit3_pips_actual', models.FloatField()),
                ('take_profit4', models.FloatField()),
                ('take_profit4_adj', models.FloatField()),
                ('take_profit4_pips_planned', models.FloatField()),
                ('take_profit4_pips_actual', models.FloatField()),
                ('take_profit5', models.FloatField()),
                ('take_profit5_adj', models.FloatField()),
                ('take_profit5_pips_planned', models.FloatField()),
                ('take_profit5_pips_actual', models.FloatField()),
                ('take_profit_count', models.IntegerField()),
                ('take_profit_total_actual', models.FloatField()),
                ('total_trades', models.IntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('strategy', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('tg_message_id', models.CharField(max_length=255)),
                ('tg_sender_id', models.CharField(max_length=255)),
                ('tg_date', models.DateTimeField(auto_now_add=True)),
                ('mt4_ticket_id', models.CharField(max_length=255)),
                ('mt4_magic_number', models.CharField(max_length=255)),
                ('mt4_open_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
